### ISSUE TITLE
Struggling

### ISSUE THREAD

**Issue by Methodise** [linouxis9/bitshares2-liquiditybots#5]
exchange-bot_1  | 2016-06-08 19:11:17.860500| Starting bot...
exchange-bot_1  | 2016-06-08 19:11:31.536569 | Amount of blocks since bot has been started: 0
exchange-bot_1  | bid ask SILVER : BTS 4900.0
exchange-bot_1  | feed SILVER : BTS 4735.849999999999
exchange-bot_1  | filled SILVER : BTS None
exchange-bot_1  | last SILVER : BTS 5000.0
exchange-bot_1  | Traceback (most recent call last):
exchange-bot_1  |   File "./exchangebots/main.py", line 79, in <module>
exchange-bot_1  |     run_bot()
exchange-bot_1  |   File "./exchangebots/main.py", line 17, in run_bot
exchange-bot_1  |     bot.init(config)
exchange-bot_1  |   File "/usr/src/app/exchangebots/bot.py", line 76, in init
exchange-bot_1  |     bots[name].init()
exchange-bot_1  |   File "/usr/src/app/exchangebots/strategies/liquidity_wall.py", line 114, in init
exchange-bot_1  |     self.tick()
exchange-bot_1  |   File "/usr/src/app/exchangebots/strategies/liquidity_wall.py", line 132, in tick
exchange-bot_1  |     print("avg weighted SILVER : BTS", self.get_price("SILVER : BTS"))
exchange-bot_1  |   File "/usr/src/app/exchangebots/strategies/liquidity_wall.py", line 338, in get_price
exchange-bot_1  |     price_weight_sum = sum([self.get_price(market, target_price=target) \* weight for target, weight in target_price.items() if self.get_price(market, target_price=target) > 0])
exchange-bot_1  |   File "/usr/src/app/exchangebots/strategies/liquidity_wall.py", line 338, in <listcomp>
exchange-bot_1  |     price_weight_sum = sum([self.get_price(market, target_price=target) \* weight for target, weight in target_price.items() if self.get_price(market, target_price=target) > 0])
exchange-bot_1  | TypeError: unorderable types: NoneType() > int()
bitshares2liquiditybots_exchange-bot_1 exited with code 1

**Comment by Methodise** [comment]
something to do with silver being finicky.

**Comment by mauritsvdvijgh** [comment]
We merged with stakemachine (will update the repo shortly to reflect that)
You can find LiqBot strategy for stake machine here: https://github.com/xeroc/stakemachine/tree/master/stakemachine/strategies
there is an updated version of liquidity_wall there which shouldn't have this issue.

**Comment by linouxis9** [comment]
@Methodise You should be able to run the new LiqBot strategy without any problem with StakeMachine.

Just install StakeMachine and change the config to use liquidity_wall (The LiqBot strategy) and maintain_collateral_ratio.
